# This is the application.properties file for the Spring Boot application.
# This is the name of the application, which can be used for logging and other purposes.

spring.application.name=firstspring
#server.port=9090